# Generated by Django 4.1.3 on 2022-11-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('N', 'Nam'), ('Nu', 'Nu'), ('K', 'Khac')], max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
