# Generated by Django 4.1.3 on 2022-11-25 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('W', 'Nu'), ('O', 'Khac')], max_length=10)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('US', 'User')], default='US', max_length=10)),
            ],
        ),
    ]
