# Generated by Django 4.1.3 on 2022-11-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$ppDPvgNiZw6burPdYTxX4C$xAzRjz6S1VJbp3bUUw1N6fSBGsI9LjElkjGzo/uJq5E=', max_length=60),
        ),
    ]
